#pragma once

enum USER_PROPERTY_CODE {
	USER_MAXHP = 1,
	USER_MAXMP = 2,
	USER_HONOR = 3,
	USER_EGO = 4,
	USER_STR = 5,
	USER_INT = 6,
	USER_DEX = 7,
	USER_VIT = 8,
	USER_LUCK = 9,
	USER_ATTACK_R = 10,
	USER_ATTACK_L = 11,
	USER_AA = 12,
	USER_AVOID = 13,
	USER_BLOCKRATE = 14,
	USER_FIRE_RESIST = 15,
	USER_ICE_RESIST = 16,
	USER_LIGHT_RESIST = 17,
	USER_POI_RESIST = 18,
	USER_PHY_RESIST = 19,
	USER_MOVESPEED = 20,
	USER_EXP = 21,
	USER_HP = 22,
	USER_MP = 23,
	USER_CASTINGTIME = 24,
	USER_COOLTIME = 25,
	USER_ATTACKRATE_PERCENT = 26,
	USER_ATTACKACURACY_PERCENT = 27,
	USER_OVERDRIVE_DELAY = 28,
	USER_HEALHPSPEED = 29,
	USER_HEALMPSPEED = 30,
	USER_POISONING = 31,
	USER_DEC_SKILLLEVEL = 32,
	USER_SKILLATTACK_R_PERCENT = 33,
	USER_SKILLATTACK_L_PERCENT = 34,
	USER_CTTIME = 35,
	USER_ALL_RESIST = 36,
	USER_MAX_RESIST = 37,
	USER_MOVESPEED_PERCENT = 38,
	USER_HEALHPSPEED_PERCENT = 39,
	USER_PHY_RESIST_PERCENT = 40,
	USER_MP_PERCENT = 41,
	USER_MAXHP_PERCENT = 42,
	USER_ATTACK_R_PERCENT = 43,
	USER_BLOCKRATE_PERCENT = 44,
	USER_AVOID_PERCENT = 45,
	USER_HP_PERCENT = 46,
	USER_POI_RESIST_PERCENT = 47,
	USER_ITEM_ATTACK = 48,
	USER_ITEM_DEFENSE = 49,
	USER_BLIND = 50,
	USER_MAXMP_PERCENT = 51,
	USER_ATTACK_L_PERCENT = 52,
	USER_DETECTION = 53,
	USER_MAX_STATUS
};

enum SELECT_ATTACK_TYPE {
	SELECT_ATTACK_TYPE_LBUTTON = 0,
	SELECT_ATTACK_TYPE_RBUTTON = 1,
};

enum UNIT_STATUS
{
	UNIT_STATUS_NONE = 0,
	UNIT_STATUS_NORMAL = 10,
	UNIT_STATUS_WALKING = 11,
	UNIT_STATUS_RUNNING = 12,
	UNIT_STATUS_ATTACKING = 13,
	UNIT_STATUS_DAMAGING = 14,
	UNIT_STATUS_SKILL = 15,
	UNIT_STATUS_CASTING = 16,
	UNIT_STATUS_WAITING = 17,
	UNIT_STATUS_DEAD = 18,
	UNIT_STATUS_READY = 19,
	UNIT_STATUS_PORTAL_MOVING = 20,
	UNIT_STATUS_PLAYER_SHOP = 21,
	UNIT_STATUS_PLAYER_REST = 22,
	UNIT_STATUS_DELAYTIME = 23,
	UNIT_STATUS_WORLD = 128,
	UNIT_STATUS_RIDE_AIRPLANE = 130,
	UNIT_STATUS_RIDE_AIRPLANE_DOWN = 131,
	UNIT_STATUS_AIRPLANE_DOWNING = 134,
	UNIT_STATUS_AIRPLANE_FLOATING = 135,
	UNIT_STATUS_AWAIT_DUNGEON_RESPONSE = 136,	//던전에 조인하기 위해 던전(월드)서버의 응답을 기다리는중 
};

enum STATUS_POINT_KIND {
	STATUS_POINT_KIND_EGO = 0,
	STATUS_POINT_KIND_STR = 1,
	STATUS_POINT_KIND_INT = 2,
	STATUS_POINT_KIND_DEX = 3,
	STATUS_POINT_KIND_VIT = 4,
	STATUS_POINT_KIND_MAX
};

enum ATTACK_MODE {
	ATTACK_MODE_NONE = 0,
	ATTACK_MODE_OFFENSE = 1,		// 공격자
	ATTACK_MODE_DEFENSE = 2,		// 방어자
};

#define		WEIGTH_100PER_OVER					101		// 소지품 무게가 100 퍼 이상인경우 
#define		WEIGTH_80PER_OVER					81		// 소지품 무게가 80 퍼 이상인경우 