chdir %~dp0

call .\setDirectoryVariables.bat

echo "Begin installing products executables & libraries from centralizedOutput"

echo "COPY IN ALL PLACES COMMONServer.dll"
echo CENTRALIZED_OUTPUT_DIR is "%CENTRALIZED_OUTPUT_DIR%"

call :COPY_IN_ALL_PLACES CommonServer.dll
call :COPY_IN_ALL_PLACES CommonServer.lib
call :COPY_IN_ALL_PLACES CommonServer.pdb

call :COPY_IN_ALL_PLACES BaseLibrary.lib
call :COPY_IN_ALL_PLACES BaseLibrary.pdb

call :COPY_IN_ALL_PLACES I4DyuchiNET.lib
call :COPY_IN_ALL_PLACES I4DyuchiNET.pdb

call :COPY_IN_ALL_PLACES SS3DGFunc.pdb
call :COPY_IN_ALL_PLACES SS3DGFunc.lib
call :COPY_IN_ALL_PLACES SS3DGFunc.dll


call :COPY_IN_ALL_PLACES SS3DFileStorage.pdb
call :COPY_IN_ALL_PLACES SS3DFileStorage.lib
call :COPY_IN_ALL_PLACES SS3DFileStorage.dll


call :COPY_IN_ALL_PLACES SS3DRendererForCorum.pdb
call :COPY_IN_ALL_PLACES SS3DRendererForCorum.lib
call :COPY_IN_ALL_PLACES SS3DRendererForCorum.dll

call :COPY_IN_ALL_PLACES SS3DGeometryForCorum.pdb
call :COPY_IN_ALL_PLACES SS3DGeometryForCorum.lib
call :COPY_IN_ALL_PLACES SS3DGeometryForCorum.dll


call :COPY_IN_ALL_PLACES SS3DExecutiveForCorum.pdb
call :COPY_IN_ALL_PLACES SS3DExecutiveForCorum.lib
call :COPY_IN_ALL_PLACES SS3DExecutiveForCorum.dll

call :CENTRALIZED_TO_LOGINSERVER LoginAgentResult.exe
call :CENTRALIZED_TO_WORLDSERVER WorldServerResult.exe
call :CENTRALIZED_TO_BEYONDE DungeonServerResult.exe
call :CENTRALIZED_TO_LUDILOR DungeonServerResult.exe
call :CENTRALIZED_TO_INSTALLED CorumOnlineResult.exe

echo "copying done"
pause

:CENTRALIZED_TO_INSTALLED
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%INSTALLED_CLIENT_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_WORLDSERVER
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%WORLDSERVER_DIR%%~1"
GOTO:EOF


:CENTRALIZED_TO_LOGINSERVER
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%LOGINSERVER_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_BEYONDE
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%DUNGEONSERVER_BEYONDE_DIR%%~1" 
GOTO:EOF 

:CENTRALIZED_TO_LUDILOR
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%DUNGEONSERVER_LUDILOS_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_CORUMONLINEPROJECT
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" %CORUMONLINEPROJECT_DIR%%~1"
GOTO:EOF

:COPY_IN_ALL_PLACES
call :CENTRALIZED_TO_INSTALLED %~1
call :CENTRALIZED_TO_WORLDSERVER %~1
call :CENTRALIZED_TO_LOGINSERVER %~1
call :CENTRALIZED_TO_BEYONDE %~1
call :CENTRALIZED_TO_LUDILOR %~1
call :CENTRALIZED_TO_CORUMONLINEPROJECT %~1
GOTO:EOF