@echo on

chdir %~dp0

call .\setDirectoryVariables.bat

echo "Begin installing products executables & libraries from centralizedOutput"

echo "COPY IN ALL PLACES"
echo CENTRALIZED_OUTPUT_DIR is "%CENTRALIZED_OUTPUT_DIR%"

call :COPY_IN_ALL_PLACES CommonServer.dll
call :COPY_IN_ALL_PLACES CommonServer.lib
call :COPY_IN_ALL_PLACES CommonServer.pdb


call :COPY_IN_ALL_PLACES BaseNetwork.dll
call :COPY_IN_ALL_PLACES BaseNetwork.lib
call :COPY_IN_ALL_PLACES BaseNetwork.pdb

call :COPY_IN_ALL_PLACES BaseLibrary.lib
call :COPY_IN_ALL_PLACES BaseLibrary.pdb
call :COPY_IN_ALL_PLACES BaseLibrary.dll

call :COPY_IN_ALL_PLACES I4DyuchiNET.lib
call :COPY_IN_ALL_PLACES I4DyuchiNET.pdb

call :COPY_IN_ALL_PLACES SS3DGFunc.pdb
call :COPY_IN_ALL_PLACES SS3DGFunc.lib
call :COPY_IN_ALL_PLACES SS3DGFunc.dll


call :COPY_IN_ALL_PLACES SS3DFileStorage.pdb
call :COPY_IN_ALL_PLACES SS3DFileStorage.lib
call :COPY_IN_ALL_PLACES SS3DFileStorage.dll


call :COPY_IN_ALL_PLACES SS3DRendererForCorum.pdb
call :COPY_IN_ALL_PLACES SS3DRendererForCorum.lib
call :COPY_IN_ALL_PLACES SS3DRendererForCorum.dll

call :COPY_IN_ALL_PLACES SS3DGeometryForCorum.pdb
call :COPY_IN_ALL_PLACES SS3DGeometryForCorum.lib
call :COPY_IN_ALL_PLACES SS3DGeometryForCorum.dll


call :COPY_IN_ALL_PLACES SS3DExecutiveForCorum.pdb
call :COPY_IN_ALL_PLACES SS3DExecutiveForCorum.lib
call :COPY_IN_ALL_PLACES SS3DExecutiveForCorum.dll

call :CENTRALIZED_TO_LOGINSERVER LoginAgentResult.exe
call :CENTRALIZED_TO_LOGINSERVER libcomservice2.dll

call :CENTRALIZED_TO_WORLDSERVER WorldServerResult.exe

call :COPY_IN_ALL_PLACES DungeonServerResult.exe
call :COPY_IN_ALL_PLACES DungeonServerResult.pdb

call :CENTRALIZED_TO_INSTALLED CorumOnlineResult.exe
call :CENTRALIZED_TO_INSTALLED CorumOnlineResult.pdb
call :CENTRALIZED_TO_INSTALLED BaseLibrary.pdb
call :CENTRALIZED_TO_INSTALLED BaseLibrary.dll
call :CENTRALIZED_TO_INSTALLED mss32.dll
call :CENTRALIZED_TO_INSTALLED SoundLib.dll

call :CENTRALIZED_TO_INSTALLED CorumPreLauncher.exe


call :CENTRALIZED_TO_FILEPACK SS3DGFunc.pdb
call :CENTRALIZED_TO_FILEPACK SS3DGFunc.lib
call :CENTRALIZED_TO_FILEPACK SS3DGFunc.dll

call :CENTRALIZED_TO_FILEPACK SS3DFileStorage.pdb
call :CENTRALIZED_TO_FILEPACK SS3DFileStorage.lib
call :CENTRALIZED_TO_FILEPACK SS3DFileStorage.dll

call :CENTRALIZED_TO_FILEPACK 4DyuchiFilePack.exe
call :CENTRALIZED_TO_FILEPACK 4DyuchiFilePack.pdb

call :CENTRALIZED_TO_CORUMONLINEPROJECT CorumPreferences.lib
call :CENTRALIZED_TO_CORUMONLINEPROJECT CorumPreferences.pdb

call :PROJECT_ROOT_DIR_TO_CENTRALIZED DUNGEON_STATIC_DATA.json
call :PROJECT_ROOT_DIR_TO_CENTRALIZED SERVER_STATIC_DATA.json

call :COPY_IN_ALL_PLACES DUNGEON_STATIC_DATA.json
call :COPY_IN_ALL_PLACES SERVER_STATIC_DATA.json

echo "copying done"
pause

:CENTRALIZED_TO_FILEPACK
mkdir "%FILEPACK_DIR%"
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%FILEPACK_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_INSTALLED
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%INSTALLED_CLIENT_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_WORLDSERVER
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%WORLDSERVER_DIR%%~1"
GOTO:EOF

:PROJECT_ROOT_DIR_TO_WORLDSERVER
COPY /Y /B "%PROJECT_ROOT_DIR%%~1" "%WORLDSERVER_DIR%%~1"
GOTO:EOF

:PROJECT_ROOT_DIR_TO_CENTRALIZED
COPY /Y /B "%PROJECT_ROOT_DIR%%~1" "%CENTRALIZED_OUTPUT_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_LOGINSERVER
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%LOGINSERVER_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_DUNGEONS
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%DUNGEONSERVER_DUNGEONS_DIR%%~1" 
GOTO:EOF 

:CENTRALIZED_TO_VILLAGES
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%DUNGEONSERVER_VILLAGES_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_PASSAGES
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%DUNGEONSERVER_PASSAGES_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_SIEGE1
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%DUNGEONSERVER_SIEGE1_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_SIEGE2
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%DUNGEONSERVER_SIEGE2_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_SIEGE3
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%DUNGEONSERVER_SIEGE3_DIR%%~1"
GOTO:EOF

:CENTRALIZED_TO_CORUMONLINEPROJECT
COPY /Y /B "%CENTRALIZED_OUTPUT_DIR%%~1" "%CORUMONLINEPROJECT_DIR%%~1"
GOTO:EOF

:COPY_IN_ALL_PLACES
call :CENTRALIZED_TO_INSTALLED %~1
call :CENTRALIZED_TO_WORLDSERVER %~1
call :CENTRALIZED_TO_LOGINSERVER %~1
call :CENTRALIZED_TO_DUNGEONS %~1
call :CENTRALIZED_TO_VILLAGES %~1
call :CENTRALIZED_TO_PASSAGES %~1
call :CENTRALIZED_TO_SIEGE1 %~1
call :CENTRALIZED_TO_SIEGE2 %~1
call :CENTRALIZED_TO_SIEGE3 %~1
call :CENTRALIZED_TO_CORUMONLINEPROJECT %~1
GOTO:EOF

